openapi: 3.0.0
info:
  title: Škola Online API (Unofficial)
  version: 1.2.0
  description: Dokumentace API vytvořená na základě reálného provozu a testování.

servers:
  - url: https://aplikace.skolaonline.cz/solapi/api

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /connect/token:
    post:
      summary: Získání přístupového tokenu
      description: Odeslání uživatelského jména a hesla. Vrací access_token.
      security: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  example: password
                username:
                  type: string
                password:
                  type: string
                client_id:
                  type: string
                  example: test_client
                scope:
                  type: string
                  example: openid offline_access profile sol_api
      responses:
        '200':
          description: Úspěšné přihlášení.
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  expires_in:
                    type: integer

  /v1/user:
    get:
      summary: Informace o uživateli
      description: Vrátí údaje o přihlášeném studentovi, včetně jeho třídy.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  personID:
                    type: string
                    description: Klíčové ID studenta pro ostatní requesty.
                  userUID:
                    type: string
                  fullName:
                    type: string
                  class:
                    type: object
                    properties:
                      id:
                        type: string
                      abbrev:
                        type: string
                      name:
                        type: string

  /v1/timeTable:
    get:
      summary: Rozvrh hodin
      description: Vrátí strukturovaný rozvrh.
      security:
        - bearerAuth: []
      parameters:
        - name: StudentId
          in: query
          required: true
          schema:
            type: string
        - name: DateFrom
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: DateTo
          in: query
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  days:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                        schoolYearId:
                          type: string
                        schedules:
                          type: array
                          items:
                            type: object
                            properties:
                              scheduledHourId:
                                type: string
                              beginTime:
                                type: string
                              endTime:
                                type: string
                              subject:
                                type: object
                                properties:
                                  name:
                                    type: string
                              room:
                                type: object
                                properties:
                                  abbrev:
                                    type: string

  /v1/students/{studentId}/marks/list:
    get:
      summary: Seznam známek (Všechny)
      description: Vrátí plochý seznam známek.
      security:
        - bearerAuth: []
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: string
        - name: SemesterId
          in: query
          required: false
          schema:
            type: string
        - name: SigningFilter
          in: query
          schema:
            type: string
            default: all
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  marks:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        subjectId:
                          type: string
                        markText:
                          type: string
                        theme:
                          type: string
                        date:
                          type: string
                        weight:
                          type: number
                        isPoints:
                          type: boolean
                  subjects:
                    type: array
                    description: Číselník předmětů (ID -> Název).
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string

  /v1/student/marks/{markId}:
    get:
      summary: Detail konkrétní známky
      description: Vrátí detail známky.
      security:
        - bearerAuth: []
      parameters:
        - name: markId
          in: path
          required: true
          schema:
            type: string
        - name: StudentId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  markText:
                    type: string
                  theme:
                    type: string
                  weight:
                    type: number
                  teacherDisplayName:
                    type: string
                  subjectName:
                    type: string

  /v1/messages/received:
    get:
      summary: Přijaté zprávy
      description: Vrátí seznam zpráv s objektem odesílatele.
      security:
        - bearerAuth: []
      parameters:
        - name: Pagination.PageNumber
          in: query
          schema:
            type: integer
            default: 1
        - name: Pagination.PageSize
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        subject:
                          type: string
                        sentDate:
                          type: string
                        text:
                          type: string
                        read:
                          type: boolean
                        sender:
                          type: object
                          properties:
                            name:
                              type: string
                            type:
                              type: string
                              description: např. employee

  /v1/students/{studentId}/homeworks:
    get:
      summary: Domácí úkoly
      description: Vrátí seznam úkolů.
      security:
        - bearerAuth: []
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: string
        - name: Filter
          in: query
          schema:
            type: string
            enum: [active, all]
            default: active
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  homeworks:
                    type: array
                    items:
                      type: object
                      properties:
                        topic:
                          type: string
                        dateTo:
                          type: string
                        detailedDescription:
                          type: string
                        attachments:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: string

  /v1/students/{studentId}/behaviors:
    get:
      summary: Chování a poznámky
      description: Vrátí pochvaly a poznámky.
      security:
        - bearerAuth: []
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: string
        - name: RecordsFilter
          in: query
          schema:
            type: string
            default: all
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  behaviors:
                    type: array
                    items:
                      type: object
                      properties:
                        kindOfBehaviorName:
                          type: string
                        date:
                          type: string
                        semesterId:
                          type: string

  /v1/timeTable/codeLists:
    get:
      summary: Číselníky rozvrhu (Pololetí)
      description: Vrátí seznam semestrů.
      security:
        - bearerAuth: []
      parameters:
        - name: studentId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  semester:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        dateFrom:
                          type: string
                        dateTo:
                          type: string

  /v1/students/{studentId}/marks/bySubject:
    get:
      summary: Známky dle předmětů
      description: Hierarchický pohled na známky.
      security:
        - bearerAuth: []
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: string
        - name: SemesterId
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  subjects:
                    type: array
                    items:
                      type: object
                      properties:
                        marks:
                          type: array
                          items:
                            type: object
                            properties:
                              markText:
                                type: string

  /v1/students/{studentId}/marks/final:
    get:
      summary: Vysvědčení
      description: Vrátí známky na vysvědčení.
      security:
        - bearerAuth: []
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  certificateTerms:
                    type: array
                    items:
                      type: object
                      properties:
                        finalMarks:
                          type: array
                          items:
                            type: object
                            properties:
                              markText:
                                type: string
                              shortcutToDisplay:
                                type: string

  /v1/student/homeworks/assignment/attachments/{attachmentId}:
    get:
      summary: Stažení přílohy úkolu
      security:
        - bearerAuth: []
      parameters:
        - name: attachmentId
          in: path
          required: true
          schema:
            type: string
        - name: StudentId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK

  /v1/marks/codeLists:
    get:
      summary: Číselníky známek
      security:
        - bearerAuth: []
      parameters:
        - name: StudentId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK